 D7 <- read.csv("~/GitHub/DataAnalysisFirstAsignment/FirstAsignment/ResultsCSV/D7.csv", header=FALSE)
  View(D7)
 d7 <- as.numeric(D7[2,"V2"])
 rest <- 1 - as.numeric(d7)
 slices <- c(d7,rest)
 lbls <- c("D7", "Rest")
 pct <- round(slices/sum(slices)*100)
 lbls <- paste(lbls,pct)
 lbls <- paste(lbls,"%",sep="")
 pie(slices, labels = lbls, col=rainbow(length(lbls)),main="D3 calculation")