D1 <- read.csv("~/GitHub/DataAnalysisFirstAsignment/FirstAsignment/ResultsCSV/D1.csv", header=FALSE)
   View(D1)
 d1 <- as.numeric(D1[2,"V2"])
 rest <- 1 - as.numeric(d1)
 slices <- c(d1,rest)
 lbls <- c("D1", "Rest")
 pct <- round(slices/sum(slices)*100)
 lbls <- paste(lbls,pct)
 lbls <- paste(lbls,"%",sep="")
 pie(slices, labels = lbls, col=rainbow(length(lbls)),main="D1 calculation")